name: Dart tests and analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Dart tests and analysis
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install Pub Dependencies
        run: dart pub get

      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Project Source
        run: dart analyze

      - name: Run tests
        run: dart test
